name: ⚡ TempMail GOD MODE SINGLE

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: ⚡ Checkout
      uses: actions/checkout@v4

    - name: 🧠 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: 🚀 Install Ultra Fast
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt --prefer-binary

    - name: ⚡ EXTREME SYSTEM BOOST
      run: |
        echo "🔥 GOD MODE ENABLED"
        export PYTHONUNBUFFERED=1
        export PYTHONOPTIMIZE=2
        export PYTHONDONTWRITEBYTECODE=1
        export MALLOC_ARENA_MAX=1
        ulimit -n 1048576 || true

    - name: 💀 RUN GOD BOT
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        echo "⚡ START GOD ENGINE"

        while true
        do
          timeout 340 python3 bot.py || echo "💥 Restart GOD"
        done
